<!--  ======== СТРАНИЦА =============================================================== -->


<div class="net">
    <table style="border-spacing: 0;">
        <tr id="tr0">   <th class="th1"></th>             <th class="th2"></th>       <?php echo $l['1/4'] ?>       <th class="th2"></th>       <?php echo $l['1/2'] ?>     <th class="th2"></th>       <?php echo $l['win_top'] ?><th class="th2"></th>      <th class="th1"></th>       <th class="th2"></th>       <th class="th1"></th></tr>
        <tr id="tr1">   <?php echo $s['unit1'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr2">   <?php echo $s['time1'] ?>         <td id="td2"></td>          <?php echo $s['uunit1'] ?>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr3">   <?php echo $s['unit2'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <?php echo $l['win_bot'] ?> <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr4">   <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['time_final'] ?><td id="td4"></td>          <?php echo $s['unit_winner'] ?><td id="td6"></td>       <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr5">   <?php echo $s['unit3'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr6">   <?php echo $s['time2'] ?>         <td id="td2"></td>          <?php echo $s['uunit2'] ?>    <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr7">   <?php echo $s['unit4'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr8">   <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td8"></td>          <td id="td9"></td></tr>

        <tr id="tr29">  <?php echo $s['unit3place1'] ?>     <td class="td_bot"></td>   <?php echo $l['place3']; ?> <td id="td11"></td>         <td id="td9"></td>          <td id="td8"></td>            <td id="td1"></td>                <td id="td6"></td>     <td id="td2"></td>          <td id="td3"></td>          <td id="td9"></td></tr>
        <tr id="tr30">  <?php echo $s['time3place'] ?>      <td id="td8"></td>         <?php echo $s['unit3place3'] ?><td id="td10"></td>      <td id="td9"></td>          <td id="td2"></td>            <td id="td1"></td>                <td id="td6"></td>     <td id="td5"></td>          <td id="td8"></td>          <td id="td9"></td></tr>
        <tr id="tr31">  <?php echo $s['unit3place2'] ?>     <td class="td_top"></td>   <td id="td9"></td>          <td id="td10"></td>         <td id="td9"></td>          <td id="td8"></td>            <td id="td1"></td>                <td id="td6"></td>     <td id="td2"></td>          <td id="td3"></td>          <td id="td9"></td></tr>
    </table>
</div>
