
<div class="net">
    <table style="border-spacing: 0;">
        <tr id="tr0">   <th class="th1"></th>             <th class="th2"></th>       <th class="th1"></th>         <th class="th2"></th>       <th class="th2"></th>       <th class="th2"></th>       <th class="th1"></th>       <th class="th2"></th>       <th class="th1"></th>     <th class="th2"></th>       <th class="th1"></th>       <th class="th2"></th>       <th class="th1"></th>       <th class="th2"></th>       <th class="th1"></th></tr>
        <tr id="tr1">   <?php echo $s['unit1'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr2">   <?php echo $s['time1'] ?>         <td id="td2"></td>          <?php echo $s['uunit1'] ?>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr3">   <?php echo $s['unit2'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr4">   <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime1'] ?>    <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['uuunit1'] ?> <td class="td_bot"></td>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr5">   <?php echo $s['unit3'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr6">   <?php echo $s['time2'] ?>         <td id="td2"></td>          <?php echo $s['uunit2'] ?>    <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr7">   <?php echo $s['unit4'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr8">   <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['tttime1'] ?> <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <?php echo $s['uuuunit1'] ?><td class="td_bot"></td>  <td id="td9"></td>          <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr9">   <?php echo $s['unit5'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr10">  <?php echo $s['time3'] ?>         <td id="td2"></td>          <?php echo $s['uunit3'] ?>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr11">  <?php echo $s['unit6'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>       <td id="td6"></td>         <td id="td6"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr12">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime2'] ?>    <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['uuunit2'] ?> <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td id="td7"></td>        <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr13">  <?php echo $s['unit7'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td6"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td7"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td id="td11"></td> </tr>
        <tr id="tr14">  <?php echo $s['time4'] ?>         <td id="td2"></td>          <?php echo $s['uunit4'] ?>    <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr15">  <?php echo $s['unit8'] ?>         <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td> </tr>
        <tr id="tr16">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td6"></td>        <td id="td6"></td>        <?php echo $s['ttttime1'] ?>  <td id="td8"></td>          <?php echo $s['uuuuunit1'] ?><td class="td_bot"></td>   <td id="td11"></td></tr>
        <tr id="tr17">  <?php echo $s['unit9'] ?>         <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr18">  <?php echo $s['time5'] ?>         <td id="td2"></td>          <?php echo $s['uunit5'] ?>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr19">  <?php echo $s['unit10'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr20">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime3'] ?>    <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['uuunit3'] ?> <td class="td_bot"></td>    <td class="td_bot"></td>  <td class="td_bot"></td>    <td id="td6"></td>          <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr21">  <?php echo $s['unit11'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr22">  <?php echo $s['time6'] ?>         <td id="td2"></td>          <?php echo $s['uunit6'] ?>    <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr23">  <?php echo $s['unit12'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr24">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['tttime2'] ?> <td id="td6"></td>          <td id="td6"></td>        <td id="td6"></td>          <?php echo $s['uuuunit2'] ?> <td class="td_top"></td>   <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr25">  <?php echo $s['unit13'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr26">  <?php echo $s['time7'] ?>         <td id="td2"></td>          <?php echo $s['uunit7'] ?>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr27">  <?php echo $s['unit14'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td class="td_l"></td>      <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr28">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime4'] ?>    <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <?php echo $s['uuunit4'] ?> <td class="td_top"></td>    <td class="td_top"></td>  <td class="td_top"></td>    <td id="td6"></td>          <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr29">  <?php echo $s['unit15'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr30">  <?php echo $s['time8'] ?>         <td id="td2"></td>          <?php echo $s['uunit8'] ?>    <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr31">  <?php echo $s['unit16'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr32">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td6"></td>          <td id="td6"></td>          <td id="td8"></td>          <?php echo $s['time_final'] ?><td id="td10"></td>       <?php echo $s['unit_winner'] ?></tr>

        <tr id="tr0"><td class="td_top">Сетка лузеров</td><td  class="td_top"></td>   <td class="td_top"></td>      <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>    <td class="td_top"></td>  <td class="td_top"></td>    <td class="td_top"></td><td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr1">   <?php echo $s['unit17'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr2">   <?php echo $s['time9'] ?>         <td id="td2"></td>          <?php echo $s['uunit9'] ?>    <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr3">   <?php echo $s['unit18'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr4">   <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime5'] ?>    <td id="td4"></td>          <?php echo $s['uuunit5'] ?> <td class="td_bot"></td>    <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr5">   <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr6">   <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['uunit10'] ?>   <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <?php echo $s['unit31'] ?>  <td class="td_bot"></td>    <td id="td10"></td>         <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr7">   <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>      <td id="td10"></td>         <td id="td9"></td>          <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr8">   <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <?php echo $s['tttime3'] ?> <td id="td6"></td>          <?php echo $s['uuuunit3'] ?><td class="td_bot"></td>  <td id="td9"></td>      <td id="td10"></td>       <td id="td9"></td>            <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr9">   <?php echo $s['unit21'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td id="td9"></td>            <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td class="td_l"></td></tr>
        <tr id="tr10">  <?php echo $s['time11'] ?>        <td id="td2"></td>          <?php echo $s['uunit11'] ?>   <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <?php echo $s['time14'] ?>    <td id="td10"></td>         <?php echo $s['unit32'] ?>  <td class="td_top"></td>    <td id="td11"></td></tr>
        <tr id="tr11">  <?php echo $s['unit22'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td class="td_l"></td> <td id="td8"></td>      <?php echo $s['unit23'] ?>     <td class="td_bot"></td>  <td id="td10"></td>           <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr12">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime6'] ?>    <td id="td4"></td>          <?php echo $s['uuunit6'] ?> <td class="td_top"></td> <?php echo $s['time10'] ?>       <td id="td8"></td>      <td class="td_l"></td>  <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr13">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr14">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['uunit12'] ?>   <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <?php echo $s['unit19'] ?><td class="td_top"></td>    <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr15">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td class="td_l"></td>      <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr16">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td8"></td>        <td id="td9"></td>      <?php echo $s['ttttime2'] ?><td id="td10"></td>       <?php echo $s['uuuuunit2'] ?> <td class="td_top"></td>    <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr17">  <?php echo $s['unit25'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr18">  <?php echo $s['time13'] ?>        <td id="td2"></td>          <?php echo $s['uunit13'] ?>   <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr19">  <?php echo $s['unit26'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr20">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime7'] ?>    <td id="td4"></td>          <?php echo $s['uuunit7'] ?> <td class="td_bot"></td>    <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr21">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td class="td_l"></td>     <td id="td8"></td>         <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>        <td id="td10"></td>         <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr22">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['uunit14'] ?>   <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>          <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr23">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>          <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr24">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <?php echo $s['tttime4'] ?> <td id="td6"></td>          <?php echo $s['uuuunit4'] ?><td class="td_bot"></td>  <td id="td9"></td>      <td id="td9"></td>        <td class="td_l"></td>          <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr25">  <?php echo $s['unit29'] ?>        <td class="td_bot"></td>    <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td class="td_l"></td>          <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr26">  <?php echo $s['time15'] ?>        <td id="td2"></td>          <?php echo $s['uunit15'] ?>   <td class="td_bot"></td>    <td id="td5"></td>          <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td class="td_l"></td>          <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr27">  <?php echo $s['unit30'] ?>        <td class="td_top"></td>    <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td class="td_l"></td>    <td id="td8"></td>    <?php echo $s['unit24'] ?>    <td class="td_top"></td>  <td id="td10"></td>             <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr28">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['ttime8'] ?>    <td id="td4"></td>          <?php echo $s['uuunit8'] ?> <td class="td_top"></td>    <?php echo $s['time12'] ?><td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td id="td10"></td>             <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr29">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td class="td_l"></td>      <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td class="td_l"></td>  <td id="td9"></td>        <td id="td10"></td>             <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr30">  <td id="td1"></td>                <td id="td2"></td>          <?php echo $s['uunit16'] ?>   <td class="td_top"></td>    <td id="td5"></td>          <td id="td6"></td>          <?php echo $s['unit20'] ?><td class="td_top"></td>    <td id="td9"></td>      <td id="td9"></td>        <td id="td10"></td>             <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
        <tr id="tr31">  <td id="td1"></td>                <td id="td2"></td>          <td id="td3"></td>            <td id="td4"></td>          <td id="td5"></td>          <td id="td6"></td>          <td id="td7"></td>        <td id="td8"></td>          <td id="td9"></td>      <td id="td9"></td>        <td id="td10"></td>             <td id="td10"></td>       <td id="td10"></td>         <td id="td10"></td>         <td id="td11"></td></tr>
    </table>
</div>
