<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Season */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Seasons', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="season-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            't_id',
            'type',
            'time:datetime',
            'admin_id',
            'time_update:datetime',
            'name',
            'unit_type',
            'time_action',
            'score_open',
            'invisible',
            'zayavka_open',
            'net_type',
            'label',
            'unit1',
            'unit2',
            'unit3',
            'unit4',
            'unit5',
            'unit6',
            'unit7',
            'unit8',
            'unit9',
            'unit10',
            'unit11',
            'unit12',
            'unit13',
            'unit14',
            'unit15',
            'unit16',
            'unit17',
            'unit18',
            'unit19',
            'unit20',
            'unit21',
            'unit22',
            'unit23',
            'unit24',
            'unit25',
            'unit26',
            'unit27',
            'unit28',
            'unit29',
            'unit30',
            'unit31',
            'unit32',
            'uunit1',
            'uunit2',
            'uunit3',
            'uunit4',
            'uunit5',
            'uunit6',
            'uunit7',
            'uunit8',
            'uunit9',
            'uunit10',
            'uunit11',
            'uunit12',
            'uunit13',
            'uunit14',
            'uunit15',
            'uunit16',
            'uuunit1',
            'uuunit2',
            'uuunit3',
            'uuunit4',
            'uuunit5',
            'uuunit6',
            'uuunit7',
            'uuunit8',
            'uuuunit1',
            'uuuunit2',
            'uuuunit3',
            'uuuunit4',
            'uuuuunit1',
            'uuuuunit2',
            'unit_winner',
            'score1',
            'score2',
            'score3',
            'score4',
            'score5',
            'score6',
            'score7',
            'score8',
            'score9',
            'score10',
            'score11',
            'score12',
            'score13',
            'score14',
            'score15',
            'score16',
            'score17',
            'score18',
            'score19',
            'score20',
            'score21',
            'score22',
            'score23',
            'score24',
            'score25',
            'score26',
            'score27',
            'score28',
            'score29',
            'score30',
            'score31',
            'score32',
            'sscore1',
            'sscore2',
            'sscore3',
            'sscore4',
            'sscore5',
            'sscore6',
            'sscore7',
            'sscore8',
            'sscore9',
            'sscore10',
            'sscore11',
            'sscore12',
            'sscore13',
            'sscore14',
            'sscore15',
            'sscore16',
            'ssscore1',
            'ssscore2',
            'ssscore3',
            'ssscore4',
            'ssscore5',
            'ssscore6',
            'ssscore7',
            'ssscore8',
            'sssscore1',
            'sssscore2',
            'sssscore3',
            'sssscore4',
            'ssssscore1',
            'ssssscore2',
            'time1',
            'time2',
            'time3',
            'time4',
            'time5',
            'time6',
            'time7',
            'time8',
            'time9',
            'time10',
            'time11',
            'time12',
            'time13',
            'time14',
            'time15',
            'time16',
            'ttime1',
            'ttime2',
            'ttime3',
            'ttime4',
            'ttime5',
            'ttime6',
            'ttime7',
            'ttime8',
            'tttime1',
            'tttime2',
            'tttime3',
            'tttime4',
            'ttttime1',
            'ttttime2',
            'time_final',
            'unit3place1',
            'unit3place2',
            'unit3place3',
            'score3place1',
            'score3place2',
            'time3place',
        ],
    ]) ?>

</div>
